export enum Routes {
  accueil = "/",
  vente = "/vente",
  admin = "/admin",
  login = "/login",
  nosrésidents = "/nosrésidents",
  produits = "/produits/:animalId/:animal/:background",
  panier = "/panier",
  notreparc = "/notreparc",
  profil = "/profil",
  connexion = "/connexion",
  laboratoire = "/laboratoire",
  billets = "/billets",
  livrasion = "/livrasion",
  loi = "/loi/:titreLoi",
}
